### PR TITLE
Enhanced navigation bar

### LINKED ISSUE #11: Enhance the Navbar
Hey Harshit @uti1man ! 
I would like to **enhance the Navbar** by adding the **hover effect** on it. Please assign me this issue.

### PR DESCRIPTION
**Pull request by amitxdewangan**
Issue fix #11 
I have enhanced the Navigation bar.

**Checklist:**
- [x] Enhanced the Navigation UI
- [x] Resolved the scrolled Navigation
- [x] Added the mouse Hover effect

Before modifying:

Screenshot 2022-10-04 001548

After modifying:

Screenshot 2022-10-04 001706

After adding mouse Hover Effect:

Screenshot 2022-10-04 001741

### CODE REVIEW

**Comment by binbard** [comment]
Great work !!
However it is not responsive for mobile screen
Checkout if it can be improved
Good luck 👍🏼

**Comment by amitxdewangan** [comment]
Thanks for pointing out that. I am working on it.

**Comment by amitxdewangan** [comment]
PR #25 updated

**Checklist**
- [x] Added responsiveness to Navigation for mobile screen.

**Comment by binbard** [comment]
Great efforts!!
But current one is more elegent atleast on mobile view.
Also current navbar has scrollbar which makes it more cleaner & compact
You can work on current one by:
 1. Reducing horizontal scrollbar size just below the tabs
 2. Reducing width for each tab (only for desktop screen) for containing more tabs

Good luck 👍

**Comment by amitxdewangan** [comment]
I have one doubt.
What do mean by the reducing horizontal scrollbar that you mentioned in point 1?
Pls, elaborate.

**Comment by binbard** [comment]
Sorry for being late
chrome_SVw7a037U4
Also these points are a bit unnecessary though, will not be accepting related changes

For you commit, I am not in favour of that hidden menubar. Current one is cool ✌🏼

**Pull request closed without merging**
