### PR TITLE
feat: added open graph

### PR DESCRIPTION
**Pull request by Nakamcode**

### CODE REVIEW

**Comment by Nakamcode** [comment]
please you didn't add the hacktoberfest label?

**Comment by Nakamcode** [comment]
Thanks

**Comment by Nakamcode** [comment]
Thanks

**Comment by Nakamcode** [comment]
Thanks

**Comment by Nakamcode** [comment]
Thanks

**Review by ericbarrionuevo — COMMENTED** [review]
revision approved

**Pull request merged**
