### PR TITLE
Updated contribution guide in readme

### PR DESCRIPTION
**Pull request by sachin-404**
Updated readme with a detailed contribution guide.

### CODE REVIEW

**Comment by binbard** [comment]
Resolve merge conflicts

**Comment by sachin-404** [comment]
Okay!

**Comment by sachin-404** [comment]
Resolved the merge conflict, have a look

**Comment by uti1man** [comment]
Great, merged
[ consider starring ⭐ the repo ]

**Comment by binbard** [comment]
@sachin-404 My mistake.
Please resend the pr

**Comment by binbard** [comment]
Perfect, merged 🎉
[ consider starring ⭐ the repo ]

**Pull request merged**
